# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.hostLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.gridLayout.addWidget(self.hostLineEdit, 0, 1, 1, 1)
        self.icmpCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.icmpCheckBox.setObjectName("icmpCheckBox")
        self.gridLayout.addWidget(self.icmpCheckBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.srcLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.srcLineEdit.setObjectName("srcLineEdit")
        self.gridLayout.addWidget(self.srcLineEdit, 1, 1, 1, 1)
        self.tcpCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.tcpCheckBox.setObjectName("tcpCheckBox")
        self.gridLayout.addWidget(self.tcpCheckBox, 1, 2, 1, 1)
        self.sniffPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sniffPushButton.setObjectName("sniffPushButton")
        self.gridLayout.addWidget(self.sniffPushButton, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dstLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dstLineEdit.setObjectName("dstLineEdit")
        self.gridLayout.addWidget(self.dstLineEdit, 2, 1, 1, 1)
        self.udpCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.udpCheckBox.setObjectName("udpCheckBox")
        self.gridLayout.addWidget(self.udpCheckBox, 2, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 490, 322))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "本机IP"))
        self.icmpCheckBox.setText(_translate("MainWindow", "ICMP"))
        self.label_2.setText(_translate("MainWindow", "源IP"))
        self.tcpCheckBox.setText(_translate("MainWindow", "TCP"))
        self.sniffPushButton.setText(_translate("MainWindow", "SNIFF!"))
        self.label_3.setText(_translate("MainWindow", "目的IP"))
        self.udpCheckBox.setText(_translate("MainWindow", "UDP"))
